"""End-to-end fidelity gate: compares the JAX port against the *actual, unmodified*
original CDDD implementation (real TF1 graph, real ``tf.contrib.rnn.MultiRNNCell``/
``tf.contrib.seq2seq.BeamSearchDecoder``, real checkpoint restore via
``tf.train.Saver``) -- not a from-scratch reimplementation of the math (that's
``tests/test_against_tf1_reference.py``).

The fixture this test reads is generated by ``scripts/run_original_model.py``,
which needs a legacy TensorFlow 1.x install (``jax-cddd-convert`` environment)
and is not required to run these tests.
"""
import os
from pathlib import Path

import jax.numpy as jnp
import numpy as np
import pytest

from jax_cddd.inference import CDDDModel
from jax_cddd.params import default_params_path

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "original_code_reference.npz"

EMB_ATOL = 1e-4
EMB_RTOL = 1e-4

pytestmark = [
    pytest.mark.skipif(not FIXTURE_PATH.exists(), reason="original_code_reference.npz fixture missing"),
    pytest.mark.skipif(
        not os.path.exists(default_params_path()),
        reason="default_model_params.npz not found; run scripts/convert_checkpoint.py first",
    ),
]


@pytest.fixture(scope="module")
def fixture():
    with np.load(FIXTURE_PATH) as data:
        return {k: data[k] for k in data.files}


@pytest.fixture(scope="module")
def model():
    return CDDDModel()


def test_embeddings_match_original_code(model, fixture):
    smiles = list(fixture["smiles"])
    expected_emb = fixture["embeddings"]

    jax_emb = model.seq_to_emb(smiles)

    max_abs_err = np.max(np.abs(jax_emb - expected_emb))
    print(f"max abs embedding error vs original code across {len(smiles)} molecules: {max_abs_err:.2e}")
    np.testing.assert_allclose(jax_emb, expected_emb, atol=EMB_ATOL, rtol=EMB_RTOL)


def test_reconstructions_match_original_code(model, fixture):
    smiles = list(fixture["smiles"])
    expected_emb = fixture["embeddings"]
    expected_recon = list(fixture["reconstructed"])
    beam_width = int(fixture["beam_width"])

    # Decode from the *original code's own* embeddings, isolating the decoder
    # comparison from any small upstream difference in the encoder.
    jax_recon = model.emb_to_seq(jnp.asarray(expected_emb), beam_width=beam_width, max_len=150)

    mismatches = [
        (s, exp, got) for s, exp, got in zip(smiles, expected_recon, jax_recon) if exp != got
    ]
    for s, exp, got in mismatches:
        print(f"mismatch for {s!r}: original={exp!r} jax={got!r}")

    assert jax_recon == expected_recon, f"{len(mismatches)}/{len(smiles)} reconstructions differ from the original code"
